image: maven:3.8.5-openjdk-11

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - mvn $MAVEN_CLI_OPTS compile

test_job:
  stage: test
  script:
    - mkdir -p src/main/resources
    - echo "Running tests..."
    - echo "api_base_url=$API_BASE_URL" > src/main/resources/config.properties
    - echo "test_user_email=$TEST_USER_EMAIL" >> src/main/resources/config.properties
    - echo "test_user_password=$TEST_USER_PASSWORD" >> src/main/resources/config.properties
    - echo "test_admin_email=$TEST_ADMIN_EMAIL" >> src/main/resources/config.properties
    - echo "test_admin_password=$TEST_ADMIN_PASSWORD" >> src/main/resources/config.properties
    - echo "API_BASE_URL configurada: ${API_BASE_URL:+SIM}"
    - grep "api_base_url" src/main/resources/config.properties
    - mvn $MAVEN_CLI_OPTS test
  needs:
    - build_job 